# Site settings
title: Sinead Naughton
email: sinead.m.naughton@gmail.com
url: https://sineadnaughton.github.io
description: "Portfolio for a full-stack software developer"
keywords: "sinead naughton, sinead naughton portfolio, software graduate, software developer, software engineer, java, web design, html, css, spring, angular, ruby, ruby on rails, rest, restful api"
skills: "A full-stack software developer who loves coding and problem solving"
meta_author: Sinead Naughton

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffb3b3 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sinead Naughton
  location: Location
  social: Online

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sineadnaughton/
  - title: github
    url: https://github.com/SineadNaughton

# Postal address (add as many lines as necessary)
address:
  - line: Cork
  - line: Ireland

# Build settings
markdown: kramdown
permalink: pretty
